language: python

python: "3.7"

services:
  - postgresql
  - redis-server
  - docker

addons:
  postgresql: "10"

env:
  global:
  - DJANGO_SETTINGS_MODULE=postfixer.conf.dev
  - SECRET_KEY=dummy
  - DB_USER=postgres
  - DB_PASSWORD=

jobs:
  include:
    - stage: Tests / Linting
      name: Django tests
      cache: pip
      install:
        - pip install -r requirements/dev.txt codecov
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src
      after_success:
        - codecov

    - name: Import ordering
      install:
        - pip install isort
      before_script: skip
      script: isort --recursive --check-only --diff .

    - name: Code style
      install:
        - pip install black
      before_script: skip
      script: black --check src

    - stage: Docker image build
      name: Test docker image build
      before_install: skip
      install: skip
      before_script: skip
      script: docker build .
      # deploy:
      #   - provider: script
      #     script: bin/docker_push.sh latest
      #     on:
      #       branch: master

      #   - provider: script
      #     script: bin/docker_push.sh $TRAVIS_TAG
      #     on:
      #       tags: true
