# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
  web:
    build: .
    image: docker.io/regexit/postfixer:${TAG:-latest}
    environment:
      - DJANGO_SETTINGS_MODULE=postfixer.conf.docker
      - SECRET_KEY=${SECRET_KEY:-@#^@cohoj8&f3-jyr^85@k%!hb*4y+bb49@x!bp8v9i6lndd==}
    ports:
      - 8000:8000
    depends_on:
      - db
