# Generated by Django 3.2.17 on 2023-02-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DKIMKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(
                        help_text="The (sub) domain, e.g. for user@example.com, enter 'example.com'.",
                        max_length=255,
                        verbose_name="domain name",
                    ),
                ),
                (
                    "selector",
                    models.CharField(
                        help_text="Key selector, these typically change during key rotation.",
                        max_length=63,
                        verbose_name="key selector",
                    ),
                ),
                (
                    "signing_algorithm",
                    models.CharField(
                        choices=[
                            ("rsa-sha1", "rsa-sha1"),
                            ("rsa-sha256", "rsa-sha256"),
                            ("ed25519-sha256", "ed25519-sha256"),
                        ],
                        default="rsa-sha256",
                        max_length=20,
                        verbose_name="signing algorithm",
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        help_text="Private key, in PEM format.",
                        verbose_name="private key",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Public key - this needs to be published in the DNS record.",
                        verbose_name="public key",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
            ],
            options={
                "verbose_name": "DKIM keypair",
                "verbose_name_plural": "DKIM keypairs",
            },
        ),
    ]
