# Generated by Django 2.2.1 on 2019-11-17 12:58

import re

import django.core.validators
from django.db import migrations, models

import django_better_admin_arrayfield.models.fields

import postfixer.mail.validators


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_auto_20191112_0848"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Domain",
        ),
        migrations.AddField(
            model_name="forward",
            name="destinations",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=320, verbose_name="destination"),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forward",
            name="domain_part",
            field=models.CharField(
                default="",
                max_length=255,
                validators=[
                    postfixer.mail.validators.validate_lowercase,
                    django.core.validators.RegexValidator(
                        regex=re.compile(
                            "((?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\\.)+)(?:[A-Z0-9-]{2,63}(?<!-))\\Z",
                            2,
                        )
                    ),
                ],
                verbose_name="domain part",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forward",
            name="user_part",
            field=models.CharField(
                default="",
                max_length=255,
                validators=[
                    postfixer.mail.validators.validate_lowercase,
                    django.core.validators.RegexValidator(
                        regex=re.compile(
                            "(^[-!#$%&'*+/=?^_`{}|~0-9A-Z]+(\\.[-!#$%&'*+/=?^_`{}|~0-9A-Z]+)*\\Z|^\"([\\001-\\010\\013\\014\\016-\\037!#-\\[\\]-\\177]|\\\\[\\001-\\011\\013\\014\\016-\\177])*\"\\Z)",
                            2,
                        )
                    ),
                ],
                verbose_name="user part",
            ),
            preserve_default=False,
        ),
    ]
