# Generated by Django 2.2.1 on 2019-11-17 12:58

from django.db import migrations


def migrate_to_split_parts(apps, _):
    Forward = apps.get_model("mail.Forward")
    for forward in Forward.objects.all():
        forward.user_part, forward.domain_part = forward.source.rsplit("@")
        forward.save()


def migrate_destinations(apps, _):
    Forward = apps.get_model("mail.Forward")
    for forward in Forward.objects.all():
        forward.destinations = [forward.destination]
        forward.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0004_auto_20191117_1358"),
    ]

    operations = [
        migrations.RunPython(migrate_to_split_parts, migrations.RunPython.noop),
        migrations.RunPython(migrate_destinations, migrations.RunPython.noop),
    ]
