# Generated by Django 2.2.1 on 2019-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0005_auto_20191117_1358"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="virtualmailbox",
            name="unique_email",
        ),
        migrations.RemoveField(
            model_name="forward",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="forward",
            name="source",
        ),
        migrations.AddConstraint(
            model_name="forward",
            constraint=models.UniqueConstraint(
                fields=("user_part", "domain_part"), name="unique_forward_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualmailbox",
            constraint=models.UniqueConstraint(
                fields=("user_part", "domain_part"), name="unique_mailbox_email"
            ),
        ),
    ]
